// <auto-generated />
namespace Entity_Nested_Structure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialMigration : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202203141301395_InitialMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVY227jNhB9L9B/EPjUFljLSYHFbmDvInXiImjtBFG6rwEtjW2iFKmSVGB/Wx/6Sf2FDiXrRvqizWaD7YshkZyZw5kzF+vfv/8ZfdykPHgCpZkUY3I2GJIARCwTJlZjkpvlm3fk44fvvxtdJ+km+FSdO7fnUFLoMVkbk12EoY7XkFI9SFmspJZLM4hlGtJEhufD4bvwbBgCqiCoKwhG97kwLIXiBV8nUsSQmZzymUyA69067kSF1mBOU9AZjWFMrlHSbB/noA0kj5FReWxyBYMraigJLjmjiCkCvvxMgMP3FiCpTaPx0tTDNoMCQGW7fQZP/QbbzgIu3SmZgTLbe1juJG8SEoRdudAVrMVaMtY4Pgnz8zkJ5jnndMFxYUm5BhJkby8iIxX8CgIURX/cUWNACSsLJdbSCRfZ235+eB8Oz60fQiqENNRgtD3gDkz7WwHFcCBxSDBlG0h+B7Ey6xrsjG6qFXwkwR+CIc9QCEMI7cuV78eNXoGOFctKfK9s+44qdO6R6OxVMqdPbFU4dK86EtwDL7b1mmUlgwc7rlcnpkqm95I3SVBuPEYyV7GNgdy3+0DVCkwXzyhsuN1evtRaxqyA0aF8BaF7pWuRBEfxlHFpboKByLlhGWcxvo3JT56XDqmsLnFS5XAwOPO0Yh6CVcMox1KjjaJMGD9pmYhZRvkxAI5Qz1y3Dq/VuztXkIGw6XrMl33sNrz0rddGnBp0yjOjsEUJvzaijEEJUB222FXY+GyxexGY9lkGmgQNF53QOmFsQXHUNDnSOrM3iVzPnOJwjboN2PPvKdr20NLxNJ7ck621t5v+GJYNsmqk4YFOOprRLMPq2Oqsu5UgKtvq5E30+Q0zLXWEsd7TN2u0tSVsVXQFzi6aRqRTprSxLXxBbb2eJKl3rBe3KlsOxfx4VYyrBOxzh1B7B4yKmX467vRM8YapzeWiL7th3yNYzDiUU7Wn+U8kz1NxuKgcli57clu+XOmvodNg24o6G/31NcWprexwybJkdnzqFTUvik5Cuaw4llLukdp6nVpOCo12dD49sXr8Lo+QAF30xBLL7WiLZEtLikV/8QlnRTGrDsyoYEvk44P8E+z0jen3/FG3HvG0Tvi3Oe8ye/mTk603DvefU8UTVfGaqh9SuvnxBWbPL9LnzpPF7Y+p+DrT23OHK1dPSchnzH5fMKW93lxW3O5/Mo35jbXHRLY9Mo+VhWtMkoXECJf0PDjPvMa05k9W3tR4kKEnJV9mIvPbBMa59fkDeabZqlFhP4YIiDsRrs/ciKWsqOYgqo44xWUGhiYY/ktl2JLGBrdj0Lr4p/yJ8tw6JV1AciNuc5PlBq8M6YJ3nGEJe8x+MXZ2MY9ui/qoX+IKCJPhFeBW/JIzntS4p37VP6TCZsKuldhYGttSVtta01yKnop27qsT+AHSDP+2g74VEX2Cw9hO+7DrsdEVoytF07YHy5Udkoii5ZYJNNCWaOzZr3eh/Xz34T8PqjxO8BMAAA=="; }
        }
    }
}
